name: Lint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  zsh-syntax-check:
    name: zsh syntax check
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5

      - name: Ensure zsh installed
        run: |
          command -v zsh || (sudo apt-get update && sudo apt-get install -y zsh)

      - name: Syntax check (install.zsh)
        run: zsh -n install.zsh
  rust-lint:
    name: rust clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@v2
      - name: Run cargo clippy
        run: cargo clippy --all-targets -- -D warnings
      - name: Run cargo fmt check
        run: cargo fmt --all -- --check

  markdown-lint:
    name: markdownlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 22
      - name: Install markdownlint-cli2
        run: npm install -g markdownlint-cli2
      - name: Run markdownlint
        run: markdownlint-cli2 .github/README.md
