name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

env:
  CARGO_TARGET_DIR: ${{ github.workspace }}/target

jobs:
  build:
    name: build (${{ matrix.target }} on ${{ matrix.runner }})
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            os: linux
            arch: x86_64
            use-cross: false
          - runner: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            os: linux
            arch: aarch64
            use-cross: true
          - runner: macos-14
            target: aarch64-apple-darwin
            os: macos
            arch: aarch64
            use-cross: false

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        if: ${{ !matrix.use-cross }}
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install cross (for cross-compiling)
        if: ${{ matrix.use-cross }}
        run: |
          cargo install cross --git https://github.com/cross-rs/cross
          rustup target add ${{ matrix.target }}

      - name: Build (cross)
        if: ${{ matrix.use-cross }}
        working-directory: rz
        run: cross build --release --target ${{ matrix.target }}

      - name: Build (cargo)
        if: ${{ !matrix.use-cross }}
        working-directory: rz
        run: cargo build --release --target ${{ matrix.target }}

      - name: Package (tar.gz)
        shell: bash
        run: |
          set -eux
          TAG="${GITHUB_REF_NAME#v}"  # "v1.2.3" -> "1.2.3"
          BIN_DIR="target/${{ matrix.target }}/release"
          DIST="rz/dist"
          mkdir -p "$DIST"

          EXE="rz"
          BASENAME="rz-v${TAG}-${{ matrix.os }}-${{ matrix.arch }}"
          PKGDIR="${DIST}/${BASENAME}"
          mkdir -p "$PKGDIR"

          cp "${BIN_DIR}/${EXE}" "${PKGDIR}/"
          chmod +x "${PKGDIR}/${EXE}" || true
          [[ -f ./LICENSE ]] && cp LICENSE "${PKGDIR}/"

          (cd "$DIST" && tar czf "${BASENAME}.tar.gz" "${BASENAME}")
          echo "ASSET=${DIST}/${BASENAME}.tar.gz" >> $GITHUB_ENV

      - name: Generate checksums
        shell: bash
        run: |
          set -eux
          cd rz/dist
          for f in *.tar.gz; do
            if command -v shasum >/dev/null 2>&1; then
              shasum -a 256 "$f" >> SHA256SUMS.txt
            else
              sha256sum "$f" >> SHA256SUMS.txt
            fi
          done

      - name: Upload release asset(s)
        uses: softprops/action-gh-release@v2
        with:
          files: |
            rz/dist/*.tar.gz
            rz/dist/SHA256SUMS.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
